# Comprehensive NumPy Assignment

**Python for Data Science – NumPy Practice Assignment**

## Instructions
- Use only the NumPy library unless specified otherwise.
- Write clean and well-commented code.
- Display outputs for every question.
- Attempt all questions.
- Explain the logic behind your solutions wherever possible.

## Part 1: Introduction to NumPy

Q1. Import NumPy and display its version.

In [1]:
import numpy as np
np.__version__


'2.4.2'

Q2. Create arrays: (1) 1-D array from 1 to 10, (2) 3x4 zeros, (3) 3x3 ones, (4) identity matrix of size 5, (5) even numbers from 2 to 20.

In [3]:
# ans - 1
arr_1d = np.arange(11, dtype = "int32")
print(f"1d array : {arr_1d}")

# ans - 2
arr_zeros = np.zeros((3, 4), dtype = "int32")
print(f"array with zero values of shape (3, 4): \n{arr_zeros}")

# ans - 3
arr_ones = np.ones((3, 3), dtype = "int32")
print(f"array with ones values of shape (3, 3): \n{arr_ones}")

# ans - 4
I = np.zeros((5, 5), dtype = "int32")
for i in range(len(I)):
    I[i][i] = 1
print(f"Identity matrix of shape (5, 5): \n{I}")

# ans - 5
arr_even = np.arange(2, 21, 2, dtype = "int32")
print(f"array with even  numbers: \n{arr_even}")

1d array : [ 0  1  2  3  4  5  6  7  8  9 10]
array with zero values of shape (3, 4): 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
array with ones values of shape (3, 3): 
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Identity matrix of shape (5, 5): 
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
array with even  numbers: 
[ 2  4  6  8 10 12 14 16 18 20]


Q3. Create arrays using np.arange(), np.linspace(), np.random.rand(), np.random.randint(), and np.full(). Explain the differences.

In [5]:
arr_with_arange = np.arange(1, 11, 2, dtype = "int32")
print(arr_with_arange)
'''arange by default start from zero, if we dont give the first parameter, but since here i give the first parameter value as 1, it will start from 1 and go upto i.e second_parameter value - 1 and use the third parameter as jump or we can say "step" condition (bydefault step uses 1), and the last parameter tell numpy the data type of the array value should be integer, because bydefault numpy uses float for numbers, but arange function takes only 1 parameter as necessary parameter that is the stoping condition'''

arr_with_linspace = np.linspace(10, 100, num = 20)
print(arr_with_linspace)
"""
  - here the first parameter tells the starting number to include in the array
  - second parameter tells that last number to include in the array
  - and num parameter tell us that number of element that should be include in the array, and except number 10 and 100 there will be 18 inner element , that numpy will automatically generate with equally space between each other
"""

arr_with_random = np.random.rand(3, 2)
print(arr_with_random)
"""
 - As the name suggest- that random function generate some random number in the shape of
   - first index tells - number of rows
   - second index tells - number of columns
"""

arr_with_full = np.full((3, 4), 5)
print(arr_with_full)
"""
 - works exactly like .zeros() and ones() but here it is free to use any number in matrix
   that contain same number in entire row and columns
 - here, it will create 3 row and 4 columns matrix in which there will be only 5 across all the rows and columns, not any other value
"""

[1 3 5 7 9]
[ 10.          14.73684211  19.47368421  24.21052632  28.94736842
  33.68421053  38.42105263  43.15789474  47.89473684  52.63157895
  57.36842105  62.10526316  66.84210526  71.57894737  76.31578947
  81.05263158  85.78947368  90.52631579  95.26315789 100.        ]
[[0.08568035 0.2927924 ]
 [0.23114909 0.93990065]
 [0.19982468 0.93930255]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


'\n - works exactly like .zeros() and ones() but here it is free to use any number in matrix\n   that contain same number in entire row and columns\n - here, it will create 3 row and 4 columns matrix in which there will be only 5 across all the rows and columns, not any other value\n'

## Array Attributes

Q4. Given arr = np.array([[10,20,30],[40,50,60],[70,80,90]]), find shape, size, dimension, dtype, itemsize, and memory occupied.

In [12]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]], dtype = "int32")
print(f"shape: {arr.shape}")
print(f"size: {arr.size}")
print(f"Dimensions: {arr.ndim}")
print(f"dtype: {arr.dtype}")
print(f"item size: {arr.size}")
print(f"memory occupied: {arr.nbytes}") # return 9 * 4 (int bytes for 32 bit architecture) = 36
# but if i change the dtype = "int64" , it will use 8 byte for integer, result = 9 * 8 = 72
arr = arr.astype(dtype = "int64")
print(f"memory occupied: {arr.nbytes}")

shape: (3, 3)
size: 9
Dimensions: 2
dtype: int32
item size: 9
memory occupied: 36
memory occupied: 72


Q5. Convert the array into float, integer, and boolean types.

In [13]:
arr = arr.astype(dtype = "float")
print(f"array with float data type: \n {arr}")

arr = arr.astype(dtype = "int64")
print(f"array with integer data types: \n {arr}")

arr = arr.astype(dtype = np.bool)
print(f"array with boolean data types: \n {arr}")


array with float data type: 
 [[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]
array with integer data types: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
array with boolean data types: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Part 3: Indexing and Slicing

###### Creata a 4x4x2 array and display the elements, rows and columns

In [20]:

arr_3d = np.array(np.arange(32).reshape(4, 4, 2), dtype = "int32")
print(f"Array: \n {arr_3d}")
print(f"all rows: \n {arr_3d[:, :, :]}")
all_columns_0 = arr_3d[:, :, 0]
all_columns_1 = arr_3d[:, :, 1]
print(f"all columns: \n {all_columns_0} \n {all_columns_1}")

Array: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]
all rows: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30 31]]]
all columns: 
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]] 
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]


Q7. Reverse the entire array, rows, and columns.

In [21]:
# reverse entire array
reversed_arr = arr_3d[::-1, ::-1, ::-1]
reversed_row_arr = arr_3d[:, ::-1, :]
reversed_col_arr = arr_3d[:, :, ::-1]

print(f"reversed array: \n {reversed_arr}")
print(f"reversed rows array: \n {reversed_row_arr}")
print(f"reversed cols array: \n {reversed_col_arr}")


reversed array: 
 [[[31 30]
  [29 28]
  [27 26]
  [25 24]]

 [[23 22]
  [21 20]
  [19 18]
  [17 16]]

 [[15 14]
  [13 12]
  [11 10]
  [ 9  8]]

 [[ 7  6]
  [ 5  4]
  [ 3  2]
  [ 1  0]]]
reversed rows array: 
 [[[ 6  7]
  [ 4  5]
  [ 2  3]
  [ 0  1]]

 [[14 15]
  [12 13]
  [10 11]
  [ 8  9]]

 [[22 23]
  [20 21]
  [18 19]
  [16 17]]

 [[30 31]
  [28 29]
  [26 27]
  [24 25]]]
reversed cols array: 
 [[[ 1  0]
  [ 3  2]
  [ 5  4]
  [ 7  6]]

 [[ 9  8]
  [11 10]
  [13 12]
  [15 14]]

 [[17 16]
  [19 18]
  [21 20]
  [23 22]]

 [[25 24]
  [27 26]
  [29 28]
  [31 30]]]


Q8. Replace values greater than 30 with 0.

In [22]:

arr_3d[arr_3d > 30] = 0
print(f"array after replace: \n {arr_3d}")

array after replace: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]
  [30  0]]]


## Part 4: Reshaping and Flattening

Q9. Create an array from 1 to 24 and reshape it into different dimensions. Compare flatten() and ravel().

In [25]:
arr = np.arange(1, 25, dtype = "int32")

In [26]:
arr = arr.reshape(4, 6)

In [27]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [28]:
arr = arr.reshape(3, 8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)

In [29]:
arr = arr.flatten()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [30]:
arr = arr.ravel()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
"""
 - the difference between .flatten() and .ravel() is
 - .flatten() -> returns a copy of the original array
 - .ravel() -> return a view of the original array, means modifying anything in the .ravel() result array will modify the original array
"""

Q10. Demonstrate transpose(), swapaxes(), and reshape(-1).

In [32]:
# transpose means - convert rows into columns and columns into rows form in a matrix, and the sape will change after transpose, for example (3, 8) -> (8, 3)
arr = arr.reshape(3, 8)
arr_T = arr.T
print(f"transpose matrix: \n {arr_T}")

arr_swapaxes = np.swapaxes(arr, 0, 1)
print(f"array after swap axes: \n {arr_swapaxes}")

arr = arr.reshape(-1)
print(f"array after reshape (-1) (flatten the array in 1d): \n {arr}")

transpose matrix: 
 [[ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]
 [ 8 16 24]]
array after swap axes: 
 [[ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]
 [ 8 16 24]]
array after reshape (-1) (flatten the array in 1d): 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


## Part 5: Mathematical Operations

Q11. Perform arithmetic operations between arrays.

In [35]:
arr_1 = np.arange(1, 11, dtype = "int32")
arr_2 = np.arange(11, 21, dtype = "int32")

In [36]:
arr_1 + arr_2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30], dtype=int32)

In [37]:
arr_1 - arr_2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10], dtype=int32)

In [38]:
arr_1 * arr_2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200], dtype=int32)

In [39]:
arr_1 / arr_2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

Q12. Find square root, exponential, logarithm, sine, cosine, and tangent values.

In [40]:
np.sqrt(arr_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [41]:
np.exp(arr_1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [42]:
np.log2(arr_2)

array([3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ,
       4.        , 4.08746284, 4.169925  , 4.24792751, 4.32192809])

In [43]:
angles = np.array([0, np.pi/4, np.pi/2])

In [44]:
np.sin(angles)

array([0.        , 0.70710678, 1.        ])

In [45]:
np.cos(angles)

array([1.00000000e+00, 7.07106781e-01, 6.12323400e-17])

In [46]:
np.tan(angles)

array([0.00000000e+00, 1.00000000e+00, 1.63312394e+16])

Q13. Compare arrays using relational operators.

In [47]:
arr_1 < arr_2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [48]:
arr_1 > arr_2


array([False, False, False, False, False, False, False, False, False,
       False])

In [49]:
arr_1 <= arr_2


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [50]:
arr_1 >= arr_2


array([False, False, False, False, False, False, False, False, False,
       False])

In [51]:
arr_1 != arr_2


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [52]:
arr_1 == arr_2


array([False, False, False, False, False, False, False, False, False,
       False])

Q14. Perform Dot product of multi dimensional array

In [53]:
arr_1 = arr_1.reshape(5, 2)
arr_2 = arr_2.reshape(2, 5)

In [54]:
arr_1 @ arr_2

array([[ 43,  46,  49,  52,  55],
       [ 97, 104, 111, 118, 125],
       [151, 162, 173, 184, 195],
       [205, 220, 235, 250, 265],
       [259, 278, 297, 316, 335]], dtype=int32)

## Part 7: Aggregation Functions

Q15. Find sum, mean, median, standard deviation, variance, maximum, and minimum.

In [55]:
arr_1.sum()

np.int64(55)

In [56]:
arr_1.mean()

np.float64(5.5)

In [57]:
np.median(arr_1)

np.float64(5.5)

In [58]:
np.std(arr_1)

np.float64(2.8722813232690143)

In [59]:
np.var(arr_1)

np.float64(8.25)

In [60]:
arr_1.max()

np.int32(10)

In [61]:
arr_1.min()

np.int32(1)

aQ16. Find row-wise and column-wise statistics.

In [62]:
arr_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)

In [63]:
np.var(arr_1[0]) # variance of first row

array([1, 2], dtype=int32)

In [65]:
np.std(arr_1[:, 0]) # std of first column

np.float64(2.8284271247461903)

Q17. Find cumulative sum and cumulative product.

In [66]:
arr_1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [67]:
arr_1.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

## Part 8: Sorting and Searching

In [68]:
sorted_arr = np.sort(arr)
print("Ascending Sort:", sorted_arr)

Ascending Sort: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [69]:
indices = np.where(sorted_arr > 5)
print("Indices where value > 5:", indices[0])

Indices where value > 5: [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Q19. Find unique elements and their frequencies.

In [70]:
unique_elements, counts = np.unique(arr, return_counts=True)
unique_elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

## Part 9: Stacking and Splitting

Q20. Demonstrate stacking methods.

In [76]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

Q21. Split arrays into equal parts.

In [83]:
matrix = np.arange(8).reshape(4, 2)
print(f"Original Matrix: \n {matrix}")

upper, lower = np.vsplit(matrix, 2)

print(f"Upper Piece: \n {upper}")
print(f"Lower Piece: \n {lower}")

Original Matrix: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
Upper Piece: 
 [[0 1]
 [2 3]]
Lower Piece: 
 [[4 5]
 [6 7]]


## Part 10: Random Module

Q22. Generate random numbers and matrices.

In [84]:
matrix = np.random.rand(10).reshape(2, 5)
matrix

array([[0.49484395, 0.38000307, 0.99852385, 0.97845804, 0.10716241],
       [0.53795417, 0.05067831, 0.07634694, 0.69158454, 0.89969665]])

Q23. Simulate rolling a die 100 times and analyze frequencies.

In [87]:
def roll():
    array = np.random.randint(1, 7, size=100)
    elements, counts = np.unique(array, return_counts=True)
    return elements, counts

elements, counts = roll()
for el, ct in zip(elements, counts):
    print(f"Number {el}: rolled {ct} times")

Number 1: rolled 18 times
Number 2: rolled 15 times
Number 3: rolled 24 times
Number 4: rolled 17 times
Number 5: rolled 12 times
Number 6: rolled 14 times


## Part 11: Boolean Masking and Filtering

Q24. Extract values based on conditions.

In [88]:
arr_1[arr_1 > 5]

array([ 6,  7,  8,  9, 10], dtype=int32)

Q25. Replace odd numbers with -1.

In [90]:
arr_1[arr_1 % 2 != 0] = -1
arr_1

array([[-1,  2],
       [-1,  4],
       [-1,  6],
       [-1,  8],
       [-1, 10]], dtype=int32)

a## Part 12: Missing Values

Q26. Detect and replace missing values.

In [93]:
arr = np.array([1, 2, 3, np.nan, 4, 5])
np.isnan(arr)

array([False, False, False,  True, False, False])

## Part 13: Linear Algebra

Q27. Perform matrix operations.

In [95]:
A = np.arange(20).reshape(4, 5)
B = np.arange(20).reshape(5, 4)
C = np.arange(20).reshape(4, 5)
print(A.dot(B))
print(A + C)
print(A.T)

[[120 130 140 150]
 [320 355 390 425]
 [520 580 640 700]
 [720 805 890 975]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Q28. Find determinant, inverse, transpose, eigenvalues, and eigenvectors.

In [101]:
A = np.random.rand(16).reshape(4, 4)
np.linalg.det(A)

np.float64(0.03562430608025486)

In [102]:
np.linalg.inv(A)

array([[  2.97468336,  -7.75372478,   5.28543038,   1.90828581],
       [ -2.95651628,  14.61658991, -12.44161424,  -2.45634388],
       [  0.97592173,   0.17509838,   0.13559017,  -0.73009752],
       [  0.51037381,  -7.85165513,   7.64439394,   2.00871262]])

In [103]:
B.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [104]:
eigenvalues, eigenvectors = np.linalg.eig(A)

In [105]:
eigenvectors

array([[-0.42064639+0.j        , -0.22584933+0.53039472j,
        -0.22584933-0.53039472j,  0.46701885+0.j        ],
       [-0.58088783+0.j        , -0.2970365 -0.07722599j,
        -0.2970365 +0.07722599j, -0.78411299+0.j        ],
       [-0.45953378+0.j        , -0.38350129-0.25388192j,
        -0.38350129+0.25388192j,  0.00114395+0.j        ],
       [-0.52388419+0.j        ,  0.60162257+0.j        ,
         0.60162257-0.j        ,  0.40872839+0.j        ]])

In [106]:
eigenvalues

array([2.39275471+0.j        , 0.21600872+0.46530462j,
       0.21600872-0.46530462j, 0.05657374+0.j        ])

Q29. Solve a system of linear equations using NumPy.

In [107]:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 2]])
B = np.array([8, 13, 8])
solution = np.linalg.solve(A, B)
print(f"x = {solution[0]}")
print(f"y = {solution[1]}")
print(f"z = {solution[2]}")

x = 1.5555555555555554
y = 1.6666666666666665
z = 3.2222222222222223


## Part 14: Advanced NumPy

Q30. Demonstrate fancy indexing, boolean indexing, where(), argmax(), argmin(), and argsort().

In [108]:
A[:, 0]

array([2, 1, 1])

In [109]:
A[A < 5]

array([2, 1, 1, 1, 3, 2, 1, 0, 2])

In [110]:
np.where(A > 10)

(array([], dtype=int64), array([], dtype=int64))

In [111]:
A.argmax(axis=0)

array([0, 1, 1])

In [112]:
A.argmin(axis=1)

array([1, 0, 1])

In [113]:
A.argsort(axis=0)

array([[1, 2, 0],
       [2, 0, 1],
       [0, 1, 2]])

Q31. Use tile(), repeat(), clip(), and diag().

In [117]:
print(f"A: \n {A}")
np.tile(A, reps=2)

A: 
 [[2 1 1]
 [1 3 2]
 [1 0 2]]


array([[2, 1, 1, 2, 1, 1],
       [1, 3, 2, 1, 3, 2],
       [1, 0, 2, 1, 0, 2]])

In [119]:
np.repeat(A, repeats=2)

array([2, 2, 1, 1, 1, 1, 1, 1, 3, 3, 2, 2, 1, 1, 0, 0, 2, 2])

In [120]:
np.clip(A)

array([[2, 1, 1],
       [1, 3, 2],
       [1, 0, 2]])

In [121]:
np.diag(A)

array([2, 3, 2])

Q32. Create a checkerboard pattern.

In [122]:
base_block = np.array([[0, 1],
                       [1, 0]])
checkerboard_tile = np.tile(base_block, (4, 4))
print(checkerboard_tile)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q33. Write a line of code to extract the inner 2×2 submatrix (excluding the border rows and columns).

In [126]:

arr_3d = np.arange(32).reshape(2, 4, 4)
submatrix = arr_3d[:, 1:-1, 1:-1]
submatrix

array([[[ 5,  6],
        [ 9, 10]],

       [[21, 22],
        [25, 26]]])

Q34. Reshape a 1D array of 12 elements (from Step 4) into a 3×4 2D matrix.

In [130]:
arr_1d = np.arange(12)

In [132]:
arr_1d = arr_1d.reshape(3, 4)
arr_1d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Q35 Create a 3×3 identity matrix.

In [134]:
I = np.zeros((3, 3), dtype = "int32")

In [135]:
for i in range(len(I)):
    I[i][i] = 1
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

Q35. Stack two identical 2×2 arrays of ones vertically.

In [140]:
I_1 = np.zeros((2, 2), dtype = "int32")
I_2 = np.zeros((2, 2), dtype = "int32")
for i in range(len(I_1)):
    I_1[i][i], I_2[i][i] = 1, 1
print(I_1)
print(I_2)

print(f"vertical stack: \n {np.vstack((I_1, I_2))}")

[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
vertical stack: 
 [[1 0]
 [0 1]
 [1 0]
 [0 1]]


Q36. Create Matrix A with dimensions 2×3 and Matrix B with dimensions 3×2.

In [141]:
A = np.arange(6).reshape(2, 3)
B = np.arange(6).reshape(3, 2)

Q37. Perform a matrix multiplication (A × B) to yield a 2×2 matrix result.

In [142]:
A.dot(B)

array([[10, 13],
       [28, 40]])

# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [145]:
#Complete the following code in order to add the vector v to each row of a matrix x:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j] = v[j] + x[i][j]
print(y)

[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]
